name: Build and deploy ASP.Net Core app to Azure Web App - ClassroomFinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: DotnetBackend

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ${{github.workspace}}/published-app
        working-directory: DotnetBackend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{github.workspace}}/published-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: downloaded-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D97C8E0C2C8B4D44AEA1B1789F8DFD68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2BA7C8F51A184AE9BF92B4E291B8820A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D56317A11924519B18AB9ABCBB6C4AE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ClassroomFinder'
          slot-name: 'Production'
          package: downloaded-app
